apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ma4ka8pqt-nodejs 
  janus-idp.io/tekton: ma4ka8pqt-nodejs
  backstage.io/kubernetes-id: ma4ka8pqt-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ma4ka8pqt-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  