apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ma4ka8pqt-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ma4ka8pqt-nodejs 
  name: ma4ka8pqt-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ma4ka8pqt-nodejs 
